### ISSUE TITLE
Gives error `cat: ...../.config/lvim-fm/mode: No such file or directory`

### ISSUE THREAD

**Issue by farzadmf** [lvim-tech/lvim-fm#1] opened 2023-05-20 21:32 UTC
Hi,

I just installed and tried to open the floating window. But I see the error I mentioned all over the place

**Comment by lvim-tech** [comment] 2023-05-21 03:38
Fixed in 4fdf9d386a.
Does it work for you?

**Comment by farzadmf** [comment] 2023-05-22 01:50
Thank you @lvim-tech , that issue seems to be fixed, but now I see this error when interacting with the file manager:
```
lvim-fm/bin/FileManager: line 178: directories: bad array subscript
```

**Comment by farzadmf** [comment] 2023-05-22 02:42
Gave it a look and it seems you're using `#!/bin/bash` in the `FileManager` script, but it's recommended to use `#!/usr/bin/env bash`

For me, `/bin/bash` is a super old version of bash, but `env bash` is the newer one

**Comment by lvim-tech** [comment] 2023-05-22 12:24
> lvim-fm/bin/FileManager: line 178: directories: bad array subscript

I can't reproduce. More info? This script not support folders and files with space.

**Comment by farzadmf** [comment] 2023-05-22 14:43
> I can't reproduce. More info?

I did mention what the issue is:

> Gave it a look and it seems you're using `#!/bin/bash` in the `FileManager` script, but it's recommended to use `#!/usr/bin/env bash`
> 
> For me, `/bin/bash` is a super old version of bash, but `env bash` is the newer one

Basically, the syntax you're using (index of `-1`) doesn't seem to be supported for older versions of bash (which `/bin/bash` on my system is pointing to)

---

> This script not support folders and files with space

Don't you think this makes the plugin very limited?

**Comment by farzadmf** [comment] 2023-05-22 14:46
I created a PR to fix the shebangs, just in case

**Closed as completed** 2023-05-22 14:58 UTC
